# Generated by Django 5.0.7 on 2024-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='smoking_habits',
            field=models.CharField(choices=[('NON-SMOKER', 'Non Smoker'), ('OCCASIONALLY', 'Occasionally'), ('REGULAR', 'Regular'), ('WANTING TO QUIT', 'Wanting To Quit')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hobbies',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/user_default.png', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_hobbies', to='users.userhobbies'),
        ),
    ]
