# Generated by Django 5.0.7 on 2024-07-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='UserHobbies',
        ),
    ]
