# Generated by Django 5.0.7 on 2024-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_drinking_habits_customuser_user_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_images',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image_1',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image_2',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image_3',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image_4',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
    ]
